// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SM.WebApi.Infrastructure;

#nullable disable

namespace SM.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206080847_transformerupdate")]
    partial class transformerupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SM.WebApi.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubstationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SM.WebApi.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Substation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Substations");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Transformer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrimaryVoltage")
                        .HasColumnType("float");

                    b.Property<double>("RatedCapacity")
                        .HasColumnType("float");

                    b.Property<double>("SecondaryVoltage")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubstationId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VectorGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId");

                    b.ToTable("Transformers");
                });

            modelBuilder.Entity("SM.WebApi.Domain.TransformerAuditReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BuchholzRelayOk")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateServiced")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OilDielectricBreakdownVoltage")
                        .HasColumnType("float");

                    b.Property<double?>("OilMoistureContentPpm")
                        .HasColumnType("float");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RequiredBdvLevel")
                        .HasColumnType("float");

                    b.Property<bool?>("SilicaGelBreatherOk")
                        .HasColumnType("bit");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<double?>("TransformerOilLevelPercent")
                        .HasColumnType("float");

                    b.Property<double?>("WindingTemperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TransformerId");

                    b.ToTable("AuditReports");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Asset", b =>
                {
                    b.HasOne("SM.WebApi.Domain.Substation", "Substation")
                        .WithMany()
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Substation", b =>
                {
                    b.HasOne("SM.WebApi.Domain.Customer", "Customer")
                        .WithMany("Substations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Transformer", b =>
                {
                    b.HasOne("SM.WebApi.Domain.Asset", "Asset")
                        .WithOne("Transformer")
                        .HasForeignKey("SM.WebApi.Domain.Transformer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SM.WebApi.Domain.Substation", null)
                        .WithMany("Transformers")
                        .HasForeignKey("SubstationId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("SM.WebApi.Domain.TransformerAuditReport", b =>
                {
                    b.HasOne("SM.WebApi.Domain.Transformer", "Transformer")
                        .WithMany("AuditReports")
                        .HasForeignKey("TransformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transformer");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Asset", b =>
                {
                    b.Navigation("Transformer");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Customer", b =>
                {
                    b.Navigation("Substations");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Substation", b =>
                {
                    b.Navigation("Transformers");
                });

            modelBuilder.Entity("SM.WebApi.Domain.Transformer", b =>
                {
                    b.Navigation("AuditReports");
                });
#pragma warning restore 612, 618
        }
    }
}
